<?php
namespace App\Services;
use App\Models\Contract;
use App\Models\Purchase;
use App\Models\Station;
use Illuminate\Support\Facades\DB;
class PurchaseService
{
    public function __construct(private NumberGenerator $numbers,private TimelineService $timeline){}
    public function create(array $data): Purchase { return DB::transaction(fn()=>$this->persist(new Purchase,$data)); }
    public function update(Purchase $purchase,array $data): Purchase { return DB::transaction(function()use($purchase,$data){$purchase->items()->delete();return $this->persist($purchase,$data);}); }
    private function persist(Purchase $purchase,array $data): Purchase
    {
        $calculated=[];$total=0;foreach($data['items'] as $index=>$row){$qty=(float)$row['quantity'];$unit=max(0,(float)$row['unit_cost']);if($qty<=0)throw new \DomainException('كمية الشراء يجب أن تكون أكبر من صفر.');$line=round($qty*$unit,2);$total+=$line;$calculated[$index]=array_merge($row,['total_cost'=>$line]);}
        $allocations=collect($data['allocations']??[])->filter(fn($r)=>(float)($r['amount']??0)>0)->groupBy(fn($r)=>(int)$r['item_index']);$contractIds=$allocations->flatten(1)->pluck('contract_id')->filter()->unique();$stationIds=$allocations->flatten(1)->pluck('station_id')->filter()->unique();$contracts=Contract::whereIn('id',$contractIds)->where('status','active')->get(['id','customer_id','currency'])->keyBy('id');if($contracts->pluck('currency')->unique()->count()>1)throw new \DomainException('لا يمكن توزيع فاتورة شراء واحدة على عقود بعملات مختلفة.');if($contracts->isNotEmpty()&&$contracts->pluck('currency')->unique()->first()!==($data['currency']??config('finance.default_currency','SAR')))throw new \DomainException('عملة فاتورة الشراء يجب أن تطابق عملة العقد الموزعة عليه.');$stations=Station::whereIn('id',$stationIds)->get(['id','customer_id'])->keyBy('id');
        foreach($allocations as $index=>$rows){if(!isset($calculated[$index]))throw new \DomainException('يوجد توزيع مرتبط ببند شراء غير موجود.');if($rows->sum(fn($r)=>(float)$r['amount'])>$calculated[$index]['total_cost']+0.01)throw new \DomainException('قيمة توزيع أحد البنود أكبر من تكلفته.');foreach($rows as $r){$customerId=(int)($r['customer_id']??0);$contractId=(int)($r['contract_id']??0);$stationId=(int)($r['station_id']??0);if($contractId&&!$contracts->has($contractId))throw new \DomainException('العقد المختار غير فعال أو غير موجود.');if($stationId&&!$stations->has($stationId))throw new \DomainException('المحطة المختارة غير موجودة.');$related=$contractId?(int)$contracts[$contractId]->customer_id:($stationId?(int)$stations[$stationId]->customer_id:$customerId);if($contractId&&$stationId&&(int)$contracts[$contractId]->customer_id!==(int)$stations[$stationId]->customer_id)throw new \DomainException('المحطة والعقد لا يتبعان نفس العميل.');if($customerId&&$related&&$customerId!==$related)throw new \DomainException('العميل لا يطابق العقد أو المحطة.');}}
        $purchase->fill(['number'=>$purchase->exists?$purchase->number:$this->numbers->unique('purchases','PUR'),'supplier_id'=>$data['supplier_id'],'supplier_invoice_no'=>$data['supplier_invoice_no']??null,'purchase_date'=>$data['purchase_date'],'currency'=>$data['currency']??config('finance.default_currency','SAR'),'total_amount'=>$total,'status'=>'confirmed','attachment'=>$data['attachment']??$purchase->attachment,'notes'=>$data['notes']??null,'created_by'=>$purchase->created_by?:auth()->id(),'updated_by'=>auth()->id()]);$purchase->save();
        $models=[];foreach($calculated as $index=>$row)$models[$index]=$purchase->items()->create($row);foreach($allocations as $index=>$rows)foreach($rows as $r){$contractId=(int)($r['contract_id']??0);$stationId=(int)($r['station_id']??0);$customerId=$r['customer_id']??null;if($contractId)$customerId=$contracts[$contractId]->customer_id;elseif($stationId)$customerId=$stations[$stationId]->customer_id;$models[$index]->allocations()->create(['customer_id'=>$customerId,'contract_id'=>$r['contract_id']??null,'station_id'=>$r['station_id']??null,'quantity'=>$r['quantity']??null,'amount'=>$r['amount'],'notes'=>$r['notes']??null]);}
        foreach($purchase->items()->with('allocations')->get()->flatMap->allocations->whereNotNull('customer_id')->groupBy('customer_id') as $customerId=>$rows)$this->timeline->record((int)$customerId,'purchase',$purchase->wasRecentlyCreated?'تسجيل مشتريات':'تعديل مشتريات',"{$purchase->number} · تكلفة مرتبطة ".number_format((float)$rows->sum('amount'),2),$purchase,null,route('purchases.show',$purchase),$purchase->purchase_date);
        return $purchase->load('supplier','items.product','items.allocations.customer','items.allocations.contract','items.allocations.station');
    }
    public function delete(Purchase $purchase): void { DB::transaction(function()use($purchase){$purchase->loadMissing('items.allocations');foreach($purchase->items->flatMap->allocations->whereNotNull('customer_id')->groupBy('customer_id') as $customerId=>$rows)$this->timeline->record((int)$customerId,'purchase','حذف فاتورة شراء',"{$purchase->number} · ".number_format((float)$rows->sum('amount'),2),null,null,null,now());$purchase->delete();}); }
}
