@extends('layouts.app')
@php
$editing=$addendum->exists;
$rows=old('items',$editing?$addendum->items->map(fn($i)=>$i->only(['product_id','quantity','requested_users','user_unit_price','unit_price','discount_value','maintenance_rate','notes']))->all():[['product_id'=>'','quantity'=>1,'requested_users'=>0,'user_unit_price'=>'','unit_price'=>0,'discount_value'=>0,'maintenance_rate'=>0]]);
$selectedOffers=old('pricing_offer_ids',$editing?$addendum->pricingOffers->pluck('id')->all():[]);
$installments=old('installments',$editing?$addendum->installments->map(fn($i)=>['name'=>$i->name,'percentage'=>$i->percentage,'due_date'=>$i->due_date->format('Y-m-d'),'net_amount'=>$i->net_amount,'notes'=>$i->notes])->all():[['name'=>'دفعة الملحق','percentage'=>100,'due_date'=>today()->format('Y-m-d'),'net_amount'=>'']]);
@endphp
@section('title',$editing?'تعديل ملحق':'ملحق عقد جديد')
@section('page-title',$editing?'تعديل الملحق '.$addendum->number:'إضافة ملحق للعقد '.$contract->number)
@section('page-subtitle','الملحق مفعل فور الحفظ وصيانته تبدأ بعد سنة من بداية خدمته')
@section('content')
<form method="post" enctype="multipart/form-data" action="{{ $editing?route('addendums.update',[$contract,$addendum]):route('addendums.store',$contract) }}" data-financial-form data-tax-rate="{{ $contract->tax_rate }}">@csrf @if($editing)@method('put')@endif<input type="hidden" name="billing_cycle" value="{{ $contract->billing_cycle }}"><input type="hidden" name="customer_id" value="{{ $contract->customer_id }}">
<div class="form-section"><div class="form-grid"><div class="form-group col-3"><label>تاريخ الملحق</label><input class="input" type="date" name="addendum_date" value="{{ old('addendum_date',$addendum->addendum_date?->format('Y-m-d')??today()->format('Y-m-d')) }}" required></div><div class="form-group col-3"><label>بداية الخدمة</label><input class="input" type="date" name="service_start_date" value="{{ old('service_start_date',$addendum->service_start_date?->format('Y-m-d')??today()->format('Y-m-d')) }}" required></div><div class="form-group col-2"><label>مرفق</label><input class="input" type="file" name="attachment" accept=".pdf,.jpg,.jpeg,.png,.webp"></div></div></div>
<div class="form-section"><div class="form-section-title"><h3>العروض والخصومات</h3></div><x-pricing-offers :offers="$pricingOffers" :selected="$selectedOffers" /></div>
<div class="form-section"><div class="form-section-title"><div><h3>بنود الملحق</h3><div class="help">أضف PTS والحساسات الإضافية كبنود هنا. لا يمكن تكرار نفس الموديول أو المنتج داخل الملحق.</div></div><button class="btn btn-sm btn-outline" type="button" data-add-line>+ بند</button></div><x-pricing-items :products="$products" :rows="$rows" /><x-financial-totals /></div>
<div class="form-section"><div class="form-section-title"><h3>دفعات الملحق</h3><button class="btn btn-sm btn-outline" type="button" data-add-installment>+ دفعة</button></div><div class="table-wrap"><table><thead><tr><th>الدفعة</th><th>النسبة</th><th>الاستحقاق</th><th>المبلغ قبل الضريبة</th><th></th></tr></thead><tbody data-installments data-next-index="{{ count($installments) }}">@foreach($installments as $i=>$r)<tr data-installment-row><td><input class="input" name="installments[{{ $i }}][name]" value="{{ $r['name']??'' }}"></td><td><input class="input" type="number" min="0" max="100" step=".01" name="installments[{{ $i }}][percentage]" value="{{ $r['percentage']??'' }}" data-installment-percentage></td><td><input class="input" type="date" name="installments[{{ $i }}][due_date]" value="{{ $r['due_date']??'' }}"></td><td><input class="input" type="number" min=".01" step=".01" name="installments[{{ $i }}][net_amount]" value="{{ $r['net_amount']??'' }}" data-installment-amount></td><td><button class="remove-row" type="button" data-remove-installment><x-ui-icon name="x" /></button></td></tr>@endforeach</tbody></table></div><template data-installment-template><tr data-installment-row><td><input class="input" name="installments[__INDEX__][name]" value="دفعة جديدة"></td><td><input class="input" type="number" min="0" max="100" step=".01" name="installments[__INDEX__][percentage]" data-installment-percentage></td><td><input class="input" type="date" name="installments[__INDEX__][due_date]" value="{{ today()->format('Y-m-d') }}"></td><td><input class="input" type="number" min=".01" step=".01" name="installments[__INDEX__][net_amount]" data-installment-amount></td><td><button class="remove-row" type="button" data-remove-installment><x-ui-icon name="x" /></button></td></tr></template></div>
<div class="form-section"><label>ملاحظات</label><textarea class="textarea" name="notes">{{ old('notes',$addendum->notes) }}</textarea></div><div class="form-actions"><button class="btn btn-primary">{{ $editing?'حفظ التعديل':'إنشاء وتفعيل الملحق' }}</button><a class="btn btn-light" href="{{ route('contracts.show',$contract) }}">إلغاء</a></div></form>
@endsection
