@extends('layouts.app')
@section('title',$addendum->number)
@section('page-title','ملحق العقد '.$addendum->number)
@section('page-subtitle','العقد '.$contract->number.' · '.$contract->customer->name)
@section('content')
<div class="card"><div class="card-header"><div><h2>{{ $addendum->number }}</h2><p>بداية التنفيذ {{ $addendum->service_start_date->format('Y-m-d') }}</p></div><div class="inline-actions">@if($addendum->status!=='cancelled'&&auth()->user()->hasPermission('addendums.update'))<a class="btn btn-light" href="{{ route('addendums.edit',[$contract,$addendum]) }}">تعديل</a>@endif @if($addendum->status==='cancelled'&&auth()->user()->hasPermission('addendums.reopen'))<form method="post" action="{{ route('addendums.reopen',[$contract,$addendum]) }}" class="inline-form">@csrf<button class="btn btn-outline">إعادة فتح</button></form>@elseif(auth()->user()->hasPermission('addendums.cancel'))<form method="post" action="{{ route('addendums.cancel',[$contract,$addendum]) }}" class="inline-form">@csrf<input type="hidden" name="cancellation_reason" value="إلغاء بواسطة المستخدم"><button class="btn btn-danger">إلغاء</button></form>@endif<a class="btn btn-outline" href="{{ route('contracts.show',$contract) }}">العودة للعقد</a></div></div><div class="detail-list"><div class="detail-item"><span>صافي الملحق</span><strong class="money">{{ number_format((float)$addendum->net_total,2) }} {{ $contract->currency }}</strong></div><div class="detail-item"><span>خصومات العروض</span><strong>{{ number_format((float)$addendum->promotional_discount_total,2) }}</strong></div><div class="detail-item"><span>الإجمالي</span><strong>{{ number_format((float)$addendum->grand_total,2) }}</strong></div><div class="detail-item"><span>الصيانة السنوية</span><strong>{{ number_format((float)$addendum->maintenance_total,2) }}</strong></div><div class="detail-item"><span>أول صيانة</span><strong>{{ optional($addendum->next_maintenance_date)->format('Y-m-d')?:'لا توجد' }}</strong></div><div class="detail-item"><span>PTS / حساسات</span><strong>{{ $addendum->pts_count }} / {{ $addendum->sensor_count }}</strong></div></div></div>
<div class="grid grid-2" style="margin-top:18px"><div class="card"><div class="card-header"><h2>البنود والمستخدمون/المناديب</h2></div><div class="table-wrap"><table><thead><tr><th>البند</th><th>المستخدمون/المناديب</th><th>المجاني</th><th>المدفوع</th><th>الصافي</th></tr></thead><tbody>@foreach($addendum->items as $item)<tr><td>{{ $item->product->name }}</td><td>{{ $item->requested_users }}</td><td>{{ $item->included_users+$item->promotional_free_users }}</td><td>{{ $item->billable_users }}</td><td class="money">{{ number_format((float)$item->line_net,2) }}</td></tr>@endforeach</tbody></table></div></div><div class="card"><div class="card-header"><h2>دفعات الملحق</h2></div><div class="table-wrap"><table><thead><tr><th>الدفعة</th><th>الاستحقاق</th><th>الإجمالي</th></tr></thead><tbody>@forelse($addendum->installments as $row)<tr><td>{{ $row->name }}</td><td>{{ $row->due_date->format('Y-m-d') }}</td><td class="money">{{ number_format((float)$row->total_amount,2) }}</td></tr>@empty<tr><td colspan="3" class="empty-state">لا توجد دفعات.</td></tr>@endforelse</tbody></table></div></div></div>
@if(auth()->user()->hasPermission('attachments.download')&&$addendum->attachments->isNotEmpty())
<div class="card" style="margin-top:18px"><div class="card-header"><h2>مرفقات الملحق</h2></div><div class="attachment-list">@foreach($addendum->attachments as $attachment)<a class="attachment-link" href="{{ route('attachments.download',$attachment) }}" target="_blank" rel="noopener"><span>📎</span><span><strong>{{ $attachment->label ?: $attachment->original_name }}</strong><small>{{ $attachment->original_name }}</small></span></a>@endforeach</div></div>
@endif
@endsection
