-- Raito Finance - Arabic permission display names
-- Safe for an existing database: updates labels only; permission codes and role assignments are unchanged.
SET NAMES utf8mb4;
START TRANSACTION;

UPDATE `permissions` SET `name`='عرض لوحة القيادة', `group_name`='dashboard', `updated_at`=NOW() WHERE `code`='dashboard.view';
UPDATE `permissions` SET `name`='عرض العملاء المحتملين ورحلة المبيعات', `group_name`='sales-leads', `updated_at`=NOW() WHERE `code`='sales-leads.view';
UPDATE `permissions` SET `name`='إضافة عميل محتمل', `group_name`='sales-leads', `updated_at`=NOW() WHERE `code`='sales-leads.create';
UPDATE `permissions` SET `name`='تعديل رحلة العميل المحتمل', `group_name`='sales-leads', `updated_at`=NOW() WHERE `code`='sales-leads.update';
UPDATE `permissions` SET `name`='إسناد العميل المحتمل لمسؤول', `group_name`='sales-leads', `updated_at`=NOW() WHERE `code`='sales-leads.assign';
UPDATE `permissions` SET `name`='تحويل العميل المحتمل إلى عميل', `group_name`='sales-leads', `updated_at`=NOW() WHERE `code`='sales-leads.convert';
UPDATE `permissions` SET `name`='إدارة مهام ومتابعات المبيعات', `group_name`='sales-leads', `updated_at`=NOW() WHERE `code`='sales-leads.tasks';
UPDATE `permissions` SET `name`='عرض مركز المهام', `group_name`='tasks', `updated_at`=NOW() WHERE `code`='tasks.view';
UPDATE `permissions` SET `name`='إضافة مهمة', `group_name`='tasks', `updated_at`=NOW() WHERE `code`='tasks.create';
UPDATE `permissions` SET `name`='تعديل المهام', `group_name`='tasks', `updated_at`=NOW() WHERE `code`='tasks.update';
UPDATE `permissions` SET `name`='إكمال وإعادة فتح المهام', `group_name`='tasks', `updated_at`=NOW() WHERE `code`='tasks.complete';
UPDATE `permissions` SET `name`='إسناد المهام لمستخدمين آخرين', `group_name`='tasks', `updated_at`=NOW() WHERE `code`='tasks.assign';
UPDATE `permissions` SET `name`='عرض العملاء', `group_name`='customers', `updated_at`=NOW() WHERE `code`='customers.view';
UPDATE `permissions` SET `name`='إضافة عميل', `group_name`='customers', `updated_at`=NOW() WHERE `code`='customers.create';
UPDATE `permissions` SET `name`='تعديل بيانات العملاء', `group_name`='customers', `updated_at`=NOW() WHERE `code`='customers.update';
UPDATE `permissions` SET `name`='عرض متابعة العملاء', `group_name`='customer-success', `updated_at`=NOW() WHERE `code`='customer-success.view';
UPDATE `permissions` SET `name`='تعديل بيانات متابعة العميل', `group_name`='customer-success', `updated_at`=NOW() WHERE `code`='customer-success.update';
UPDATE `permissions` SET `name`='عرض لوحة متابعة العملاء', `group_name`='customer-success', `updated_at`=NOW() WHERE `code`='customer-success.dashboard';
UPDATE `permissions` SET `name`='إدارة تنبيهات متابعة العميل', `group_name`='customer-success', `updated_at`=NOW() WHERE `code`='customer-success.flags.manage';
UPDATE `permissions` SET `name`='تحديث رضا العميل', `group_name`='customer-success', `updated_at`=NOW() WHERE `code`='customer-success.health.update';
UPDATE `permissions` SET `name`='إدارة جهات اتصال العميل', `group_name`='customer-success', `updated_at`=NOW() WHERE `code`='customer-success.contacts.manage';
UPDATE `permissions` SET `name`='عرض خطط متابعة العميل', `group_name`='customer-success', `updated_at`=NOW() WHERE `code`='customer-success.playbooks.view';
UPDATE `permissions` SET `name`='إدارة وحسم خطط المتابعة', `group_name`='customer-success', `updated_at`=NOW() WHERE `code`='customer-success.playbooks.manage';
UPDATE `permissions` SET `name`='بدء خطة متابعة للعميل', `group_name`='customer-success', `updated_at`=NOW() WHERE `code`='customer-success.playbooks.run';
UPDATE `permissions` SET `name`='إسناد مهام متابعة العميل', `group_name`='customer-success', `updated_at`=NOW() WHERE `code`='customer-success.tasks.assign';
UPDATE `permissions` SET `name`='إكمال مهام متابعة العميل', `group_name`='customer-success', `updated_at`=NOW() WHERE `code`='customer-success.tasks.complete';
UPDATE `permissions` SET `name`='إدارة فرص البيع والتوسع للعميل', `group_name`='customer-success', `updated_at`=NOW() WHERE `code`='customer-success.signals.manage';
UPDATE `permissions` SET `name`='عرض عروض المبيعات', `group_name`='quotations', `updated_at`=NOW() WHERE `code`='quotations.view';
UPDATE `permissions` SET `name`='إنشاء عرض مبيعات', `group_name`='quotations', `updated_at`=NOW() WHERE `code`='quotations.create';
UPDATE `permissions` SET `name`='تعديل عروض المبيعات', `group_name`='quotations', `updated_at`=NOW() WHERE `code`='quotations.update';
UPDATE `permissions` SET `name`='تغيير حالة عرض المبيعات', `group_name`='quotations', `updated_at`=NOW() WHERE `code`='quotations.status';
UPDATE `permissions` SET `name`='تحويل عرض المبيعات إلى عقد', `group_name`='quotations', `updated_at`=NOW() WHERE `code`='quotations.convert';
UPDATE `permissions` SET `name`='عرض تقارير عروض المبيعات', `group_name`='quotations', `updated_at`=NOW() WHERE `code`='quotations.reports';
UPDATE `permissions` SET `name`='عرض العروض والخصومات', `group_name`='pricing-offers', `updated_at`=NOW() WHERE `code`='pricing-offers.view';
UPDATE `permissions` SET `name`='إضافة عرض أو خصم', `group_name`='pricing-offers', `updated_at`=NOW() WHERE `code`='pricing-offers.create';
UPDATE `permissions` SET `name`='تعديل العروض والخصومات', `group_name`='pricing-offers', `updated_at`=NOW() WHERE `code`='pricing-offers.update';
UPDATE `permissions` SET `name`='عرض العقود', `group_name`='contracts', `updated_at`=NOW() WHERE `code`='contracts.view';
UPDATE `permissions` SET `name`='إنشاء عقد', `group_name`='contracts', `updated_at`=NOW() WHERE `code`='contracts.create';
UPDATE `permissions` SET `name`='تعديل العقود', `group_name`='contracts', `updated_at`=NOW() WHERE `code`='contracts.update';
UPDATE `permissions` SET `name`='إلغاء العقود', `group_name`='contracts', `updated_at`=NOW() WHERE `code`='contracts.cancel';
UPDATE `permissions` SET `name`='إعادة فتح العقود', `group_name`='contracts', `updated_at`=NOW() WHERE `code`='contracts.reopen';
UPDATE `permissions` SET `name`='عرض ملاحق العقود', `group_name`='addendums', `updated_at`=NOW() WHERE `code`='addendums.view';
UPDATE `permissions` SET `name`='إضافة ملحق عقد', `group_name`='addendums', `updated_at`=NOW() WHERE `code`='addendums.create';
UPDATE `permissions` SET `name`='تعديل ملاحق العقود', `group_name`='addendums', `updated_at`=NOW() WHERE `code`='addendums.update';
UPDATE `permissions` SET `name`='إلغاء ملاحق العقود', `group_name`='addendums', `updated_at`=NOW() WHERE `code`='addendums.cancel';
UPDATE `permissions` SET `name`='إعادة فتح ملاحق العقود', `group_name`='addendums', `updated_at`=NOW() WHERE `code`='addendums.reopen';
UPDATE `permissions` SET `name`='عرض الاستحقاقات', `group_name`='receivables', `updated_at`=NOW() WHERE `code`='receivables.view';
UPDATE `permissions` SET `name`='إضافة استحقاق', `group_name`='receivables', `updated_at`=NOW() WHERE `code`='receivables.create';
UPDATE `permissions` SET `name`='تعديل الاستحقاقات', `group_name`='receivables', `updated_at`=NOW() WHERE `code`='receivables.update';
UPDATE `permissions` SET `name`='عرض سندات القبض', `group_name`='collections', `updated_at`=NOW() WHERE `code`='collections.view';
UPDATE `permissions` SET `name`='إنشاء سند قبض', `group_name`='collections', `updated_at`=NOW() WHERE `code`='collections.create';
UPDATE `permissions` SET `name`='تعديل سندات القبض', `group_name`='collections', `updated_at`=NOW() WHERE `code`='collections.update';
UPDATE `permissions` SET `name`='إلغاء سندات القبض', `group_name`='collections', `updated_at`=NOW() WHERE `code`='collections.cancel';
UPDATE `permissions` SET `name`='إعادة فتح سندات القبض', `group_name`='collections', `updated_at`=NOW() WHERE `code`='collections.reopen';
UPDATE `permissions` SET `name`='عرض سندات الخصم', `group_name`='discount-vouchers', `updated_at`=NOW() WHERE `code`='discount-vouchers.view';
UPDATE `permissions` SET `name`='إنشاء سند خصم', `group_name`='discount-vouchers', `updated_at`=NOW() WHERE `code`='discount-vouchers.create';
UPDATE `permissions` SET `name`='تعديل سندات الخصم', `group_name`='discount-vouchers', `updated_at`=NOW() WHERE `code`='discount-vouchers.update';
UPDATE `permissions` SET `name`='إلغاء سندات الخصم', `group_name`='discount-vouchers', `updated_at`=NOW() WHERE `code`='discount-vouchers.cancel';
UPDATE `permissions` SET `name`='إعادة فتح سندات الخصم', `group_name`='discount-vouchers', `updated_at`=NOW() WHERE `code`='discount-vouchers.reopen';
UPDATE `permissions` SET `name`='عرض المشتريات', `group_name`='purchases', `updated_at`=NOW() WHERE `code`='purchases.view';
UPDATE `permissions` SET `name`='إضافة عملية شراء', `group_name`='purchases', `updated_at`=NOW() WHERE `code`='purchases.create';
UPDATE `permissions` SET `name`='تعديل المشتريات', `group_name`='purchases', `updated_at`=NOW() WHERE `code`='purchases.update';
UPDATE `permissions` SET `name`='حذف المشتريات', `group_name`='purchases', `updated_at`=NOW() WHERE `code`='purchases.delete';
UPDATE `permissions` SET `name`='عرض المصروفات', `group_name`='expenses', `updated_at`=NOW() WHERE `code`='expenses.view';
UPDATE `permissions` SET `name`='إضافة مصروف', `group_name`='expenses', `updated_at`=NOW() WHERE `code`='expenses.create';
UPDATE `permissions` SET `name`='تعديل المصروفات', `group_name`='expenses', `updated_at`=NOW() WHERE `code`='expenses.update';
UPDATE `permissions` SET `name`='إلغاء المصروفات', `group_name`='expenses', `updated_at`=NOW() WHERE `code`='expenses.cancel';
UPDATE `permissions` SET `name`='إعادة فتح المصروفات', `group_name`='expenses', `updated_at`=NOW() WHERE `code`='expenses.reopen';
UPDATE `permissions` SET `name`='حذف المصروفات', `group_name`='expenses', `updated_at`=NOW() WHERE `code`='expenses.delete';
UPDATE `permissions` SET `name`='عرض كشوف البنك', `group_name`='bank-statements', `updated_at`=NOW() WHERE `code`='bank-statements.view';
UPDATE `permissions` SET `name`='إضافة كشف بنك', `group_name`='bank-statements', `updated_at`=NOW() WHERE `code`='bank-statements.create';
UPDATE `permissions` SET `name`='مراجعة وتعديل حركات كشف البنك', `group_name`='bank-statements', `updated_at`=NOW() WHERE `code`='bank-statements.update';
UPDATE `permissions` SET `name`='اعتماد كشف البنك', `group_name`='bank-statements', `updated_at`=NOW() WHERE `code`='bank-statements.approve';
UPDATE `permissions` SET `name`='حذف كشوف البنك', `group_name`='bank-statements', `updated_at`=NOW() WHERE `code`='bank-statements.delete';
UPDATE `permissions` SET `name`='عرض المنتجات والموديولات', `group_name`='products', `updated_at`=NOW() WHERE `code`='products.view';
UPDATE `permissions` SET `name`='إضافة منتج أو موديول', `group_name`='products', `updated_at`=NOW() WHERE `code`='products.create';
UPDATE `permissions` SET `name`='تعديل المنتجات والموديولات', `group_name`='products', `updated_at`=NOW() WHERE `code`='products.update';
UPDATE `permissions` SET `name`='عرض الموردين', `group_name`='suppliers', `updated_at`=NOW() WHERE `code`='suppliers.view';
UPDATE `permissions` SET `name`='إضافة مورد', `group_name`='suppliers', `updated_at`=NOW() WHERE `code`='suppliers.create';
UPDATE `permissions` SET `name`='تعديل بيانات الموردين', `group_name`='suppliers', `updated_at`=NOW() WHERE `code`='suppliers.update';
UPDATE `permissions` SET `name`='عرض الوسطاء', `group_name`='intermediaries', `updated_at`=NOW() WHERE `code`='intermediaries.view';
UPDATE `permissions` SET `name`='إضافة وسيط', `group_name`='intermediaries', `updated_at`=NOW() WHERE `code`='intermediaries.create';
UPDATE `permissions` SET `name`='تعديل بيانات الوسطاء', `group_name`='intermediaries', `updated_at`=NOW() WHERE `code`='intermediaries.update';
UPDATE `permissions` SET `name`='عرض وإدارة عمولات الوسطاء', `group_name`='intermediaries', `updated_at`=NOW() WHERE `code`='intermediaries.commissions';
UPDATE `permissions` SET `name`='سداد عمولات الوسطاء', `group_name`='intermediaries', `updated_at`=NOW() WHERE `code`='intermediaries.pay-commissions';
UPDATE `permissions` SET `name`='عرض المحطات', `group_name`='stations', `updated_at`=NOW() WHERE `code`='stations.view';
UPDATE `permissions` SET `name`='تعديل بيانات المحطات', `group_name`='stations', `updated_at`=NOW() WHERE `code`='stations.update';
UPDATE `permissions` SET `name`='عرض التركيبات', `group_name`='installations', `updated_at`=NOW() WHERE `code`='installations.view';
UPDATE `permissions` SET `name`='إضافة عملية تركيب', `group_name`='installations', `updated_at`=NOW() WHERE `code`='installations.create';
UPDATE `permissions` SET `name`='تعديل عمليات التركيب', `group_name`='installations', `updated_at`=NOW() WHERE `code`='installations.update';
UPDATE `permissions` SET `name`='إلغاء عمليات التركيب', `group_name`='installations', `updated_at`=NOW() WHERE `code`='installations.cancel';
UPDATE `permissions` SET `name`='إعادة فتح عمليات التركيب', `group_name`='installations', `updated_at`=NOW() WHERE `code`='installations.reopen';
UPDATE `permissions` SET `name`='عرض تقرير الربحية', `group_name`='reports', `updated_at`=NOW() WHERE `code`='reports.profitability';
UPDATE `permissions` SET `name`='عرض تقارير العقود والاستحقاقات', `group_name`='reports', `updated_at`=NOW() WHERE `code`='reports.contracts';
UPDATE `permissions` SET `name`='عرض كشوف حساب العملاء', `group_name`='reports', `updated_at`=NOW() WHERE `code`='reports.statements';
UPDATE `permissions` SET `name`='تصدير وطباعة التقارير', `group_name`='reports', `updated_at`=NOW() WHERE `code`='reports.exports';
UPDATE `permissions` SET `name`='عرض سجل التدقيق', `group_name`='reports', `updated_at`=NOW() WHERE `code`='reports.audit';
UPDATE `permissions` SET `name`='عرض عمليات الاستيراد', `group_name`='imports', `updated_at`=NOW() WHERE `code`='imports.view';
UPDATE `permissions` SET `name`='بدء عملية استيراد', `group_name`='imports', `updated_at`=NOW() WHERE `code`='imports.create';
UPDATE `permissions` SET `name`='اعتماد الاستيراد', `group_name`='imports', `updated_at`=NOW() WHERE `code`='imports.commit';
UPDATE `permissions` SET `name`='إلغاء عملية الاستيراد', `group_name`='imports', `updated_at`=NOW() WHERE `code`='imports.cancel';
UPDATE `permissions` SET `name`='تحميل المرفقات', `group_name`='attachments', `updated_at`=NOW() WHERE `code`='attachments.download';
UPDATE `permissions` SET `name`='حذف المرفقات', `group_name`='attachments', `updated_at`=NOW() WHERE `code`='attachments.delete';
UPDATE `permissions` SET `name`='عرض المستخدمين', `group_name`='users', `updated_at`=NOW() WHERE `code`='users.view';
UPDATE `permissions` SET `name`='إضافة مستخدم', `group_name`='users', `updated_at`=NOW() WHERE `code`='users.create';
UPDATE `permissions` SET `name`='تعديل المستخدمين', `group_name`='users', `updated_at`=NOW() WHERE `code`='users.update';
UPDATE `permissions` SET `name`='إدارة الأدوار والصلاحيات', `group_name`='users', `updated_at`=NOW() WHERE `code`='users.roles';
UPDATE `permissions` SET `name`='عرض الحركات التي أدخلها المستخدم فقط', `group_name`='transactions', `updated_at`=NOW() WHERE `code`='transactions.view-own';

COMMIT;

SELECT COUNT(*) AS `permission_count` FROM `permissions`;
