@extends('layouts.app')
@section('title',$offer->exists?'تعديل عرض التسعير':'عرض تسعير جديد')
@section('page-title',$offer->exists?'تعديل '.$offer->name:'إنشاء عرض أو خصم')
@section('page-subtitle','القواعد تُطبّق من الخادم لضمان صحة الحساب')
@section('content')
<form method="post" data-pricing-offer-form data-startup-discount="{{ config('finance.startup_discount_percentage',50) }}" action="{{ $offer->exists?route('pricing-offers.update',$offer):route('pricing-offers.store') }}">@csrf @if($offer->exists)@method('put')@endif
<div class="form-section"><div class="form-grid offer-basic-grid"><div class="form-group col-7 offer-name-group"><label class="required">اسم العرض</label><input class="input" name="name" value="{{ old('name',$offer->name) }}" required></div><div class="form-group col-3"><label>النوع</label><select class="select" name="type" data-offer-type><option value="startup_discount" @selected(old('type',$offer->type)==='startup_discount')>خصم الشركات الناشئة</option><option value="seasonal_discount" @selected(old('type',$offer->type)==='seasonal_discount')>خصم موسمي</option><option value="free_users" @selected(old('type',$offer->type)==='free_users')>مستخدمون مجانيون</option><option value="bundle_fixed_discount" @selected(old('type',$offer->type)==='bundle_fixed_discount')>خصم باقة بمبلغ ثابت</option></select></div>
<div class="form-group col-3"><label>فئة العميل</label><select class="select" name="customer_segment" data-offer-segment><option value="all" @selected(old('customer_segment',$offer->customer_segment?:'all')==='all')>كل العملاء</option><option value="standard" @selected(old('customer_segment',$offer->customer_segment)==='standard')>العملاء العاديون</option><option value="startup" @selected(old('customer_segment',$offer->customer_segment)==='startup')>الشركات الناشئة</option></select></div><div class="form-group col-3"><label>دورية الفوترة</label><select class="select" name="billing_cycle" data-offer-cycle>@foreach($cycles as $v=>$l)<option value="{{ $v }}" @selected(old('billing_cycle',$offer->billing_cycle?:'all')===$v)>{{ $l }}</option>@endforeach</select></div><div class="form-group col-3" data-discount-fields><label>نسبة الخصم</label><input class="input" type="number" min="0" max="100" step=".01" name="discount_percentage" data-offer-discount value="{{ old('discount_percentage',$offer->discount_percentage?:0) }}"><div class="help" data-offer-discount-help>خصم الشركات الناشئة ثابت {{ config('finance.startup_discount_percentage',50) }}%، والموسمي تحدد نسبته.</div></div><div class="form-group col-3" data-fixed-discount-fields><label>قيمة الخصم الثابت</label><input class="input" type="number" min="0" step="0.01" name="fixed_discount_amount" data-offer-fixed-discount value="{{ old('fixed_discount_amount',$offer->fixed_discount_amount?:0) }}"><div class="help">يطبق مرة واحدة على الباقة بالكامل عند وجود كل المنتجات المحددة.</div></div><div class="form-group col-3"><label>الأولوية</label><input class="input" type="number" min="1" max="1000" name="priority" value="{{ old('priority',$offer->priority?:100) }}"></div>
<div class="form-group col-3" data-free-user-fields><label>الحد الأدنى للمستخدمين</label><input class="input" type="number" min="0" name="minimum_users" value="{{ old('minimum_users',$offer->minimum_users?:0) }}"></div><div class="form-group col-3" data-free-user-fields><label>المستخدمون المجانيون</label><input class="input" type="number" min="0" name="free_users" value="{{ old('free_users',$offer->free_users?:0) }}"></div><div class="form-group col-3" data-free-user-fields><label><input type="checkbox" name="repeat_for_each_threshold" value="1" @checked(old('repeat_for_each_threshold',$offer->repeat_for_each_threshold))> تكرار العرض لكل حد</label><div class="help">مثال: كل 4 مستخدمين يحصل على مستخدم مجاني.</div></div><div class="form-group col-3"><label>من تاريخ</label><input class="input" type="date" name="starts_at" value="{{ old('starts_at',optional($offer->starts_at)->format('Y-m-d')) }}"></div><div class="form-group col-3"><label>إلى تاريخ</label><input class="input" type="date" name="ends_at" value="{{ old('ends_at',optional($offer->ends_at)->format('Y-m-d')) }}"></div>
</div></div>
<div class="form-section"><div class="form-section-title"><div><h3>المنتجات المشمولة</h3><div class="help">في الخصومات العادية: اتركها فارغة ليطبق العرض على الكل. في خصم الباقة: حدد منتجين على الأقل، ويجب وجودهم جميعًا معًا لتطبيق الخصم.</div></div></div><div class="offer-selector">@php($selected=collect(old('product_ids',$offer->exists?$offer->products->pluck('id')->all():[])))@foreach($products as $product)<label class="offer-card"><input type="checkbox" name="product_ids[]" value="{{ $product->id }}" @checked($selected->contains($product->id))><span class="offer-check"><x-ui-icon name="check" /></span><span><strong>{{ $product->name }}</strong></span></label>@endforeach</div></div>
<div class="form-section"><div class="form-grid"><div class="form-group col-8"><label>ملاحظات</label><textarea class="textarea" name="notes">{{ old('notes',$offer->notes) }}</textarea></div><div class="form-group col-2"><label><input type="checkbox" name="is_stackable" value="1" @checked(old('is_stackable',$offer->exists?$offer->is_stackable:true))> قابل للجمع</label></div><div class="form-group col-2"><label><input type="checkbox" name="is_active" value="1" @checked(old('is_active',$offer->exists?$offer->is_active:true))> فعال</label></div></div></div>
<div class="form-actions"><button class="btn btn-primary">حفظ العرض</button><a class="btn btn-light" href="{{ route('pricing-offers.index') }}">إلغاء</a></div></form>
@endsection
