@extends('layouts.app')
@section('title','عروض وخصومات التسعير')
@section('page-title','عروض وخصومات التسعير')
@section('page-subtitle','إدارة الخصومات الموسمية والباقات والمستخدمين المجانيين')
@section('content')
<div class="card"><div class="card-header"><div><h2>العروض</h2><p>العروض الفعالة فقط تظهر في عروض المبيعات والعقود.</p></div>@if(auth()->user()->hasPermission('pricing-offers.create'))<a class="btn btn-primary" href="{{ route('pricing-offers.create') }}">+ عرض تسعير</a>@endif</div>
<form class="filters"><div class="form-group search"><label>بحث</label><input class="input" name="q" value="{{ request('q') }}" placeholder="الاسم أو الكود"></div><button class="btn btn-light">بحث</button></form>
<div class="table-wrap"><table><thead><tr><th>العرض</th><th>النوع</th><th>التطبيق</th><th>القيمة</th><th>الفترة</th><th>المنتجات</th><th>الحالة</th><th></th></tr></thead><tbody>@forelse($offers as $offer)<tr><td><strong>{{ $offer->name }}</strong><div class="muted">{{ $offer->code }}</div></td><td>{{ ['startup_discount'=>'خصم شركات ناشئة','seasonal_discount'=>'خصم موسمي','free_users'=>'مستخدمون مجانيون','bundle_fixed_discount'=>'خصم باقة ثابت'][$offer->type] }}</td><td>{{ $offer->billing_cycle==='all'?'كل الدوريات':(\App\Support\FinanceOptions::billingCycles()[$offer->billing_cycle]??$offer->billing_cycle) }}</td><td class="money">@if($offer->type==='free_users'){{ $offer->free_users }} مجاني عند {{ $offer->minimum_users }}@elseif($offer->type==='bundle_fixed_discount'){{ number_format((float)$offer->fixed_discount_amount,2) }} مبلغ ثابت@else{{ number_format((float)$offer->discount_percentage,2) }}%@endif</td><td>{{ optional($offer->starts_at)->format('Y-m-d')?:'مفتوح' }} — {{ optional($offer->ends_at)->format('Y-m-d')?:'مفتوح' }}</td><td>{{ $offer->products_count?:'الكل' }}</td><td><span class="badge {{ $offer->is_active?'badge-success':'badge-dark' }}">{{ $offer->is_active?'فعال':'موقوف' }}</span></td><td>@if(auth()->user()->hasPermission('pricing-offers.update'))<a class="btn btn-sm btn-light" href="{{ route('pricing-offers.edit',$offer) }}">تعديل</a>@endif</td></tr>@empty<tr><td colspan="8" class="empty-state">لا توجد عروض تسعير.</td></tr>@endforelse</tbody></table></div>{{ $offers->links() }}</div>
@endsection
