@extends('layouts.app')
@section('title','مراجعة كشف البنك')
@section('page-title','مراجعة ومطابقة كشف البنك')
@section('page-subtitle',$batch->original_filename.' · '.$batch->currency)
@section('content')
@php($reviewedCount=$counts['ready']+$counts['ignored']+$counts['posted'])
@php($reviewPercent=$batch->total_rows>0?min(100,round(($reviewedCount/$batch->total_rows)*100)):0)
<div class="reconcile-steps"><span class="done">1 رفع الملف</span><span class="done">2 ربط الأعمدة</span><span class="{{ $batch->status==='approved'?'done':'active' }}">3 مراجعة الحركات</span><span class="{{ $batch->status==='approved'?'done':'' }}">4 الاعتماد</span></div>

<div class="bank-review-header">
    <div class="bank-review-title"><span class="bank-icon">▦</span><div><strong>{{ $batch->bank_name ?: 'كشف حساب بنك' }}</strong><span>{{ $batch->account_name ?: 'حساب غير محدد' }} · {{ $batch->currency }}</span></div></div>
    <div class="bank-review-kpis"><div><span>الحركات</span><strong>{{ $batch->total_rows }}</strong></div><div class="out"><span>خارج</span><strong>{{ number_format((float)$batch->total_debit,2) }}</strong></div><div class="in"><span>داخل</span><strong>{{ number_format((float)$batch->total_credit,2) }}</strong></div><div><span>جاهز</span><strong>{{ $reviewedCount }}/{{ $batch->total_rows }}</strong></div></div>
    <div class="bank-review-actions"><a class="btn btn-light" href="{{ route('bank-statements.original',$batch) }}">الملف الأصلي</a>@if($batch->status!=='approved'&&auth()->user()->hasPermission('bank-statements.delete'))<form method="post" action="{{ route('bank-statements.destroy',$batch) }}" data-confirm="حذف كشف البنك غير المعتمد؟">@csrf @method('delete')<button class="btn btn-danger">حذف</button></form>@endif</div>
</div>

<div class="bank-progress-panel"><div><strong>نسبة المراجعة {{ $reviewPercent }}%</strong><span>@if($counts['draft'])متبقي {{ $counts['draft'] }} حركة تحتاج حفظ@elseكل الحركات جاهزة للاعتماد@endif</span></div><progress class="bank-progress-native" value="{{ $reviewPercent }}" max="100" aria-label="نسبة مراجعة كشف البنك {{ $reviewPercent }}%"></progress>@if($batch->status==='reviewing'&&auth()->user()->hasPermission('bank-statements.approve'))<form method="post" action="{{ route('bank-statements.approve',$batch) }}" data-confirm="اعتماد كشف البنك وإنشاء كل سندات المصروف والتحصيل؟" data-submit-lock>@csrf<button class="btn btn-primary" @disabled($counts['draft']>0)>اعتماد وإنشاء السندات</button></form>@endif</div>

<div class="card bank-review-toolbar"><form method="get" class="filter-grid compact-filter"><div class="form-group"><label>نوع الحركة</label><select class="select" name="classification"><option value="">الكل</option><option value="expense" @selected(request('classification')==='expense')>مصروف</option><option value="collection" @selected(request('classification')==='collection')>تحصيل</option><option value="ignored" @selected(request('classification')==='ignored')>متجاهل</option></select></div><div class="form-group"><label>المراجعة</label><select class="select" name="status"><option value="">الكل</option><option value="draft" @selected(request('status')==='draft')>يحتاج مراجعة</option><option value="ready" @selected(request('status')==='ready')>جاهز</option><option value="posted" @selected(request('status')==='posted')>تم الترحيل</option></select></div><div class="filter-actions"><button class="btn btn-light">تطبيق</button>@if(request()->hasAny(['classification','status']))<a class="btn btn-light" href="{{ route('bank-statements.show',$batch) }}">مسح</a>@endif</div></form></div>

<div class="bank-worklist">
@forelse($rows as $row)
<details class="bank-work-item" data-bank-row-card @if($row->status==='draft') open @endif>
    <summary class="bank-work-summary">
        <div class="bank-work-no">{{ $row->row_number }}</div>
        <div class="bank-work-desc"><strong>{{ $row->description }}</strong><span>{{ $row->transaction_date?->format('Y-m-d') ?: 'تاريخ غير صالح' }} @if($row->reference_no)· مرجع {{ $row->reference_no }}@endif</span></div>
        <div class="bank-work-type"><span class="badge {{ $row->classification==='collection'?'badge-success':($row->classification==='expense'?'badge-warning':'badge-dark') }}">{{ ['collection'=>'تحصيل','expense'=>'مصروف','ignored'=>'متجاهل'][$row->classification]??'غير مصنف' }}</span></div>
        <div class="bank-work-amount {{ $row->direction==='in'?'is-in':'is-out' }}"><strong>{{ $row->direction==='in'?'+':'-' }} {{ number_format((float)$row->amount,2) }}</strong><span>{{ $batch->currency }}</span></div>
        <div class="bank-work-status"><span class="badge {{ $row->status==='posted'?'badge-success':($row->status==='ready'?'badge-info':($row->status==='ignored'?'badge-dark':'badge-warning')) }}">{{ ['draft'=>'راجع','ready'=>'جاهز','ignored'=>'متجاهل','posted'=>'مرحّل'][$row->status]??$row->status }}</span></div>
    </summary>
    <div class="bank-work-body">
        <div class="bank-source-strip"><span>المدين <b>{{ number_format((float)$row->debit,2) }}</b></span><span>الدائن <b>{{ number_format((float)$row->credit,2) }}</b></span><span>المرجع <b>{{ $row->reference_no ?: '—' }}</b></span></div>
        @if($row->status==='posted')
            <div class="alert alert-success">تم إنشاء {{ $row->generated_type===\App\Models\Collection::class?'سند قبض':'سند مصروف' }} من الحركة. @if($row->generated_type===\App\Models\Collection::class)<a href="{{ route('collections.index',['q'=>$row->generated?->number]) }}">فتح السند</a>@elseif($row->generated_type===\App\Models\Expense::class)<a href="{{ route('expenses.index',['q'=>$row->generated?->number]) }}">فتح المصروف</a>@endif</div>
        @elseif($batch->status==='reviewing'&&auth()->user()->hasPermission('bank-statements.update'))
        <form method="post" action="{{ route('bank-statements.rows.update',[$batch,$row]) }}" data-bank-row-form data-amount="{{ $row->amount }}" data-outstanding-url="{{ route('bank-statements.outstanding',$batch) }}">@csrf @method('put')
            <div class="bank-classification-bar"><label>صنّف الحركة</label><select class="select" name="classification" data-bank-classification><option value="expense" @selected($row->classification==='expense')>مصروف</option><option value="collection" @selected($row->classification==='collection')>تحصيل</option><option value="ignored" @selected($row->classification==='ignored')>تجاهل الحركة</option></select><span>النظام اقترح النوع حسب اتجاه الحركة ويمكنك تغييره.</span></div>
            <div class="bank-detail-panel" data-bank-expense-panel>
                <div class="panel-title"><strong>بيانات المصروف</strong><span>المبلغ والتاريخ مأخوذان من البنك ولا يمكن تغييرهما.</span></div>
                <div class="form-grid"><div class="form-group col-3"><label class="required">التصنيف</label><select class="select" name="expense_category_id"><option value="">اختر</option>@foreach($expenseCategories as $category)<option value="{{ $category->id }}" @selected((int)$row->expense_category_id===$category->id)>{{ $category->name }}</option>@endforeach</select></div><div class="form-group col-5"><label class="required">البيان</label><input class="input" name="expense_description" value="{{ old('expense_description',$row->expense_description ?: $row->description) }}"></div><div class="form-group col-4"><label>المستفيد</label><input class="input" name="beneficiary" value="{{ $row->beneficiary }}"></div><div class="form-group col-4"><label>العميل - اختياري</label><select class="select" name="expense_customer_id" data-parent-customer data-remote-url="{{ route('lookup.customers') }}"><option value="">بدون عميل</option>@foreach($customers as $customer)<option value="{{ $customer->id }}" @selected((int)$row->expense_customer_id===$customer->id)>{{ $customer->name }}</option>@endforeach</select></div><div class="form-group col-4"><label>العقد - اختياري</label><select class="select" name="expense_contract_id" data-dependent-contract data-remote-url="{{ route('lookup.contracts') }}"><option value="">بدون عقد</option>@foreach($contracts as $contract)<option value="{{ $contract->id }}" data-customer="{{ $contract->customer_id }}" @selected((int)$row->expense_contract_id===$contract->id)>{{ $contract->number }}</option>@endforeach</select></div></div>
            </div>
            <div class="bank-detail-panel" data-bank-collection-panel>
                <div class="panel-title"><strong>بيانات التحصيل</strong><span>اختر العميل ثم وزع المبلغ بالكامل على الاستحقاقات.</span></div>
                <div class="form-grid"><div class="form-group col-5"><label class="required">العميل</label><select class="select" name="collection_customer_id" data-bank-collection-customer data-remote-url="{{ route('lookup.customers') }}"><option value="">اختر العميل</option>@foreach($customers as $customer)<option value="{{ $customer->id }}" @selected((int)$row->collection_customer_id===$customer->id)>{{ $customer->name }}</option>@endforeach</select></div><div class="form-group col-4"><label>ملاحظات التحصيل</label><input class="input" name="collection_notes" value="{{ $row->collection_notes }}"></div><div class="form-group col-3 action-align"><button class="btn btn-outline" type="button" data-bank-load-receivables>توزيع تلقائي</button></div><div class="col-12"><div class="bank-allocation-head"><span data-bank-allocation-summary></span><span class="bank-inline-feedback" data-bank-allocation-feedback role="status" aria-live="polite"></span></div><div class="bank-allocation-list" data-bank-allocations>@foreach(($row->allocation_data??[]) as $i=>$allocation)@php($receivable=$allocationReceivables[$allocation['receivable_id']]??null)@if($receivable)<div class="allocation-row" data-bank-allocation-row><div><strong>{{ $receivable->number }} · {{ $receivable->name }}</strong><small>متبقي {{ number_format((float)$receivable->remaining_amount,2) }} · {{ $receivable->due_date->format('Y-m-d') }}</small><input type="hidden" name="allocations[{{ $i }}][receivable_id]" value="{{ $receivable->id }}"></div><input class="input" type="number" step="0.01" min="0" name="allocations[{{ $i }}][amount]" value="{{ $allocation['amount'] }}" data-bank-allocation-amount><button type="button" class="btn btn-sm btn-danger" data-bank-remove-allocation>حذف</button></div>@endif @endforeach</div></div></div>
            </div>
            <div class="bank-row-save"><button class="btn btn-primary">حفظ الحركة</button><span>لن يتم إنشاء سند فعلي إلا بعد اعتماد الكشف بالكامل.</span></div>
        </form>
        @elseif($row->status==='ignored')<div class="alert alert-info">تم تجاهل هذه الحركة ولن ينتج عنها سند.</div>@endif
    </div>
</details>
@empty<div class="card empty-state">لا توجد حركات مطابقة للفلاتر.</div>@endforelse
</div>
{{ $rows->links() }}
@endsection
