@extends('layouts.app')
@section('title','كشف حساب '.$customer->name)
@section('page-title','كشف حساب العميل')
@section('page-subtitle',$customer->name.' · '.$customer->code)
@section('content')
<div class="card"><div class="card-header"><div><h2>{{ $customer->name }}</h2><p>الدفعات التي حل موعدها وسندات القبض وسندات الخصم</p></div><div class="inline-actions"><a class="btn btn-outline" href="{{ route('customers.statement.print',array_merge(['customer'=>$customer],request()->query())) }}" target="_blank">طباعة</a><a class="btn btn-outline" href="{{ route('customers.statement.pdf',array_merge(['customer'=>$customer],request()->query())) }}">PDF</a><a class="btn btn-outline" href="{{ route('customers.statement.excel',array_merge(['customer'=>$customer],request()->query())) }}">Excel</a></div></div>
<form class="filters" method="get"><div class="form-group"><label>العملة</label><select class="select" name="currency">@foreach($currencies as $code=>$label)<option value="{{ $code }}" @selected($currency===$code)>{{ $label }}</option>@endforeach</select></div><div class="form-group"><label>من</label><input class="input" type="date" name="from" value="{{ request('from') }}"></div><div class="form-group"><label>إلى</label><input class="input" type="date" name="to" value="{{ $to }}"></div><div class="form-group"><label>العقد</label><select class="select" name="contract_id" data-smart-select="1"><option value="">كل العقود</option>@foreach($contracts as $contract)<option value="{{ $contract->id }}" @selected(request('contract_id')==$contract->id)>{{ $contract->number }}</option>@endforeach</select></div><div class="form-group"><label>نوع الحركة</label><select class="select" name="movement"><option value="all" @selected($movement==='all')>كل الحركات</option><option value="receivables" @selected($movement==='receivables')>الاستحقاقات</option><option value="collections" @selected($movement==='collections')>سندات القبض</option><option value="discounts" @selected($movement==='discounts')>سندات الخصم</option><option value="overdue" @selected($movement==='overdue')>المتأخر فقط</option><option value="maintenance" @selected($movement==='maintenance')>الصيانة</option><option value="subscriptions" @selected($movement==='subscriptions')>الاشتراكات</option><option value="addendums" @selected($movement==='addendums')>ملحقات العقد</option></select></div><button class="btn btn-secondary">عرض</button></form>
<div class="grid grid-3 statement-summary" style="margin-bottom:16px"><div class="detail-item"><span>الرصيد الافتتاحي</span><strong class="money">{{ number_format($statement['opening'],2) }} {{ $currency }}</strong></div><div class="detail-item"><span>مدين خلال الفترة</span><strong class="money">{{ number_format($statement['debit'],2) }} {{ $currency }}</strong></div><div class="detail-item"><span>القبض والخصومات</span><strong class="money text-success">{{ number_format($statement['credit'],2) }} {{ $currency }}</strong></div><div class="detail-item"><span>متأخر حتى اليوم</span><strong class="money text-danger">{{ number_format($statement['overdue'],2) }} {{ $currency }}</strong></div><div class="detail-item"><span>استحقاقات قادمة</span><strong class="money">{{ number_format($statement['upcoming'],2) }} {{ $currency }}</strong></div><div class="detail-item"><span>الرصيد النهائي</span><strong class="money {{ $statement['closing']>0?'text-danger':'text-success' }}">{{ number_format($statement['closing'],2) }} {{ $currency }}</strong></div></div>
<div class="table-wrap"><table><thead><tr><th>التاريخ</th><th>نوع الحركة</th><th>المرجع</th><th>البيان</th><th>مدين</th><th>دائن</th><th>الرصيد</th></tr></thead><tbody>
@if($statement['opening']!=0)<tr><td>{{ request('from')?:'قبل الفترة' }}</td><td><span class="badge badge-dark">رصيد سابق</span></td><td>—</td><td>رصيد ما قبل الفترة</td><td class="money">{{ $statement['opening']>0?number_format($statement['opening'],2):'—' }}</td><td class="money">{{ $statement['opening']<0?number_format(abs($statement['opening']),2):'—' }}</td><td class="money">{{ number_format($statement['opening'],2) }}</td></tr>@endif
@forelse($statement['rows'] as $row)<tr><td>{{ $row['entry']->entry_date->format('Y-m-d') }}</td><td><span class="badge {{ $row['entry']->entry_type==='receivable'?'badge-info':'badge-success' }}">{{ $row['label'] }}</span></td><td>{{ $row['entry']->reference_no }}</td><td>{{ $row['entry']->description }}</td><td class="money">{{ $row['entry']->debit>0?number_format((float)$row['entry']->debit,2):'—' }}</td><td class="money text-success">{{ $row['entry']->credit>0?number_format((float)$row['entry']->credit,2):'—' }}</td><td class="money">{{ number_format($row['balance'],2) }}</td></tr>@empty<tr><td colspan="7" class="empty-state">لا توجد حركات مستحقة في الفترة المحددة.</td></tr>@endforelse
</tbody></table></div></div>
@endsection
