@extends('layouts.app')
@section('title','تقرير عروض المبيعات')
@section('page-title','تحليل عروض المبيعات')
@section('page-subtitle','التحويل والرفض والمنتجات ومصادر العملاء وأثر الخصومات')
@section('content')
<form class="toolbar"><input class="input" type="date" name="from" value="{{ $from }}"><input class="input" type="date" name="to" value="{{ $to }}"><select class="select" name="currency">@foreach($currencies as $code=>$label)<option value="{{ $code }}" @selected($currency===$code)>{{ $label }}</option>@endforeach</select><button class="btn btn-light">تحديث</button></form>
<div class="kpi-grid"><div class="kpi-card"><span>عدد العروض</span><strong>{{ $summary['count'] }}</strong></div><div class="kpi-card"><span>قيمة العروض</span><strong>{{ number_format($summary['value'],2) }} {{ $currency }}</strong></div><div class="kpi-card"><span>قيمة العروض المفتوحة</span><strong>{{ number_format($summary['open_value'],2) }}</strong></div><div class="kpi-card"><span>نسبة التحويل</span><strong>{{ $summary['conversion_rate'] }}%</strong></div><div class="kpi-card"><span>متوسط قيمة العرض</span><strong>{{ number_format($summary['average_value'],2) }}</strong></div><div class="kpi-card"><span>متوسط الإغلاق</span><strong>{{ $summary['average_close_days'] }} يوم</strong></div><div class="kpi-card"><span>الخصومات اليدوية</span><strong>{{ number_format($summary['manual_discount'],2) }}</strong></div><div class="kpi-card"><span>خصومات العروض</span><strong>{{ number_format($summary['promotional_discount'],2) }}</strong></div><div class="kpi-card"><span>خصم الشركات الناشئة</span><strong>{{ number_format((float)($startupSummary->discount_total??0),2) }}</strong><small>{{ $startupSummary->count??0 }} عرض</small></div></div>
<div class="grid grid-2"><div class="card"><div class="card-header"><h2>حسب الحالة</h2></div><div class="table-wrap"><table><thead><tr><th>الحالة</th><th>العدد</th><th>القيمة</th></tr></thead><tbody>@foreach($byStatus as $r)<tr><td>{{ $statuses[$r->status]??$r->status }}</td><td>{{ $r->count }}</td><td class="money">{{ number_format((float)$r->value,2) }}</td></tr>@endforeach</tbody></table></div></div><div class="card"><div class="card-header"><h2>حسب مسؤول المبيعات</h2></div><div class="table-wrap"><table><thead><tr><th>المسؤول</th><th>العروض</th><th>المتحول</th><th>القيمة</th></tr></thead><tbody>@foreach($byOwner as $r)<tr><td>{{ $r->owner }}</td><td>{{ $r->count }}</td><td>{{ $r->converted_count }}</td><td class="money">{{ number_format((float)$r->value,2) }}</td></tr>@endforeach</tbody></table></div></div></div>
<div class="card" style="margin-top:18px"><div class="card-header"><div><h2>الأداء حسب نوع النشاط</h2><p>ERP / محطات / أخرى داخل نفس العملة والفترة.</p></div></div><div class="table-wrap"><table><thead><tr><th>النشاط</th><th>العروض</th><th>المتحول</th><th>القيمة</th></tr></thead><tbody>@forelse($byActivity as $r)<tr><td>{{ $activities[$r->activity_type]??$r->activity_type }}</td><td>{{ $r->count }}</td><td>{{ $r->converted_count }}</td><td class="money">{{ number_format((float)$r->value,2) }}</td></tr>@empty<tr><td colspan="4" class="empty-state">لا توجد بيانات.</td></tr>@endforelse</tbody></table></div></div>
<div class="grid grid-2" style="margin-top:18px"><div class="card"><div class="card-header"><h2>المنتجات والموديولات الأكثر طلبًا</h2></div><div class="table-wrap"><table><thead><tr><th>البند</th><th>عدد العروض</th><th>الكمية</th><th>القيمة</th></tr></thead><tbody>@forelse($topProducts as $r)<tr><td>{{ $r->name }}</td><td>{{ $r->quotation_count }}</td><td>{{ $r->requested_quantity }}</td><td class="money">{{ number_format((float)$r->quoted_value,2) }}</td></tr>@empty<tr><td colspan="4" class="empty-state">لا توجد بيانات.</td></tr>@endforelse</tbody></table></div></div><div class="card"><div class="card-header"><h2>الأداء حسب مصدر العميل</h2></div><div class="table-wrap"><table><thead><tr><th>المصدر</th><th>العروض</th><th>المتحول</th><th>القيمة</th></tr></thead><tbody>@forelse($bySource as $r)<tr><td>{{ $r->source }}</td><td>{{ $r->count }}</td><td>{{ $r->converted_count }}</td><td class="money">{{ number_format((float)$r->value,2) }}</td></tr>@empty<tr><td colspan="4" class="empty-state">لا توجد بيانات.</td></tr>@endforelse</tbody></table></div></div></div>
<div class="grid grid-2" style="margin-top:18px"><div class="card"><div class="card-header"><h2>أسباب الرفض</h2></div><div class="table-wrap"><table><thead><tr><th>السبب</th><th>العدد</th></tr></thead><tbody>@forelse($reasons as $r)<tr><td>{{ $r->rejection_reason }}</td><td>{{ $r->count }}</td></tr>@empty<tr><td colspan="2" class="empty-state">لا توجد بيانات.</td></tr>@endforelse</tbody></table></div></div><div class="card"><div class="card-header"><h2>أثر العروض الترويجية</h2></div><div class="table-wrap"><table><thead><tr><th>العرض</th><th>الاستخدام</th><th>المتحول</th><th>الخصم</th><th>المبيعات</th><th>ربحية العقود المتحولة</th></tr></thead><tbody>@forelse($offers as $r)<tr><td>{{ $r->name }}</td><td>{{ $r->uses_count }}</td><td>{{ $r->converted_count }}</td><td class="money">{{ number_format((float)$r->discount_total,2) }}</td><td class="money">{{ number_format((float)$r->sales_value,2) }}</td><td class="money {{ (float)$r->contractual_profit<0?'text-danger':'text-success' }}">{{ number_format((float)$r->contractual_profit,2) }}</td></tr>@empty<tr><td colspan="6" class="empty-state">لا توجد عروض مستخدمة.</td></tr>@endforelse</tbody></table></div></div></div>
<div class="card" style="margin-top:18px"><div class="card-header"><div><h2>عروض تنتهي خلال 15 يومًا</h2><p>العروض المرسلة أو تحت التفاوض فقط.</p></div></div><div class="table-wrap"><table><thead><tr><th>العرض</th><th>العميل</th><th>الانتهاء</th><th>القيمة</th><th></th></tr></thead><tbody>@forelse($expiringSoon as $q)<tr><td>{{ $q->number }}</td><td>{{ $q->customer->name }}</td><td>{{ $q->valid_until->format('Y-m-d') }}</td><td class="money">{{ number_format((float)$q->grand_total,2) }}</td><td><a class="btn btn-sm btn-light" href="{{ route('quotations.show',$q) }}">فتح</a></td></tr>@empty<tr><td colspan="5" class="empty-state">لا توجد عروض قريبة من الانتهاء.</td></tr>@endforelse</tbody></table></div></div>
@endsection
