@extends('layouts.app')
@section('title',$product->exists?'تعديل بند':'إضافة بند')
@section('page-title',$product->exists?'تعديل المنتج أو الموديول':'إضافة منتج أو موديول')
@section('page-subtitle','حدد تسعير المستخدمين لكل دورية مرة واحدة')
@section('content')
<form method="post" action="{{ $product->exists?route('products.update',$product):route('products.store') }}">@csrf @if($product->exists)@method('put')@endif
<div class="form-section"><div class="form-section-title"><h3>بيانات البند</h3></div><div class="form-grid">
<div class="form-group col-8"><label class="required">الاسم</label><input class="input" name="name" value="{{ old('name',$product->name) }}" required></div><div class="form-group col-4"><label>النوع</label><select class="select" name="type">@foreach($types as $v=>$l)<option value="{{ $v }}" @selected(old('type',$product->type)===$v)>{{ $l }}</option>@endforeach</select></div>
<div class="form-group col-3"><label>الوحدة</label><select class="select" name="unit">@foreach($units as $v=>$l)<option value="{{ $v }}" @selected(old('unit',$product->unit?:'service')===$v)>{{ $l }}</option>@endforeach</select></div><div class="form-group col-3"><label>السعر الأساسي</label><input class="input" type="number" min="0" step=".01" name="default_sale_price" value="{{ old('default_sale_price',$product->default_sale_price?:0) }}"><div class="help">يمكن أن يكون صفرًا للمنتج الذي يُحاسب بالكامل حسب المستخدم مثل تطبيق المناديب.</div></div><div class="form-group col-3"><label>الدورية الافتراضية</label><select class="select" name="billing_cycle">@foreach($cycles as $v=>$l)<option value="{{ $v }}" @selected(old('billing_cycle',$product->billing_cycle?:'one_time')===$v)>{{ $l }}</option>@endforeach</select></div><div class="form-group col-3"><label>الصيانة %</label><input class="input" type="number" min="0" max="100" step="1" name="default_maintenance_rate" value="{{ (int) old('default_maintenance_rate',$product->default_maintenance_rate?:0) }}"><div class="help">صفر يعني بدون صيانة، وتُطبق على الرخصة الدائمة فقط.</div></div><div class="form-group col-6"><label>يتطلب وجود بند آخر</label><select class="select" name="required_product_id"><option value="">لا يوجد</option>@foreach($dependencyProducts as $dependency)<option value="{{ $dependency->id }}" @selected((string)old('required_product_id',$product->required_product_id)===(string)$dependency->id)>{{ $dependency->name }}</option>@endforeach</select><div class="help">مثال: تطبيق المناديب يتطلب وجود المخزون في العقد.</div></div>
</div></div>
<div class="form-section" data-user-pricing-section><div class="form-section-title"><div><h3>تسعير المستخدمين</h3><div class="help">فعّلها للموديولات التي يُحسب سعرها حسب عدد المستخدمين.</div></div><label class="switch-label"><input type="checkbox" name="supports_user_pricing" value="1" data-user-pricing-toggle @checked(old('supports_user_pricing',$product->supports_user_pricing))><span>يدعم تسعير المستخدمين</span></label></div><div class="form-grid" data-user-pricing-fields>
<div class="form-group col-3"><label>المستخدمون المجانيون - رخصة</label><input class="input" type="number" min="0" step="1" name="included_users_one_time" value="{{ old('included_users_one_time',$product->exists?$product->included_users_one_time:config('finance.included_users_per_module_one_time',3)) }}"><div class="help">الموديولات المعتادة 3، وتطبيق المناديب 0 لأن كل مندوب يُحاسب.</div></div><div class="form-group col-3"><label>سعر المستخدم - شراء مرة واحدة</label><input class="input" type="number" min="0" step=".01" name="extra_user_price_one_time" value="{{ old('extra_user_price_one_time',$product->extra_user_price_one_time?:0) }}"></div><div class="form-group col-3"><label>سعر المستخدم شهريًا</label><input class="input" type="number" min="0" step=".01" name="user_price_monthly" value="{{ old('user_price_monthly',$product->user_price_monthly?:0) }}"></div><div class="form-group col-3"><label>سعر المستخدم سنويًا</label><input class="input" type="number" min="0" step=".01" name="user_price_annual" value="{{ old('user_price_annual',$product->user_price_annual?:0) }}"></div>
</div></div>
<div class="form-section"><div class="form-grid"><div class="form-group col-12"><label>الوصف</label><textarea class="textarea" name="description">{{ old('description',$product->description) }}</textarea></div><div class="form-group col-12"><label><input type="checkbox" name="is_active" value="1" @checked(old('is_active',$product->exists?$product->is_active:true))> البند نشط</label></div></div></div>
<div class="form-actions"><button class="btn btn-primary">حفظ البند</button><a class="btn btn-light" href="{{ route('products.index') }}">إلغاء</a></div></form>
@endsection
