@extends('layouts.app')
@section('title',$installation->number)
@section('page-title','عملية التركيب '.$installation->number)
@section('page-subtitle',$installation->customer->name.' · العقد '.$installation->contract->number)
@section('content')
@php($installedPts=$installation->stations->where('status','!=','cancelled')->sum(fn($r)=>$r->pts_installed?1:0))
@php($installedSensors=$installation->stations->where('status','!=','cancelled')->sum('sensor_count'))
<div class="toolbar"><a class="btn btn-light" href="{{ route('installations.index') }}">العودة</a>@if($installation->status!=='cancelled'&&auth()->user()->hasPermission('installations.update'))<a class="btn btn-primary" href="{{ route('installations.edit',$installation) }}">تعديل</a>@endif @if($installation->status==='cancelled'&&auth()->user()->hasPermission('installations.reopen'))<form method="post" action="{{ route('installations.reopen',$installation) }}">@csrf<button class="btn btn-outline">إعادة فتح</button></form>@elseif(auth()->user()->hasPermission('installations.cancel'))<form method="post" action="{{ route('installations.cancel',$installation) }}">@csrf<input type="hidden" name="cancellation_reason" value="إلغاء بواسطة المستخدم"><button class="btn btn-danger">إلغاء</button></form>@endif</div><div class="card"><div class="detail-list"><div class="detail-item"><span>تاريخ التنفيذ</span><strong>{{ optional($installation->installation_date)->format('Y-m-d')?:'—' }}</strong></div><div class="detail-item"><span>الفريق</span><strong>{{ $installation->team_name?:'—' }}</strong></div><div class="detail-item"><span>الحالة</span><strong>{{ $installation->status }}</strong></div><div class="detail-item"><span>PTS في العملية</span><strong>{{ $installedPts }} من {{ $allowedPts }}</strong></div><div class="detail-item"><span>الحساسات في العملية</span><strong>{{ $installedSensors }} من {{ $allowedSensors }}</strong></div></div></div>
@if(auth()->user()->hasPermission('attachments.download')&&$installation->attachments->isNotEmpty())<div class="card" style="margin-top:18px"><div class="card-header"><h2>المرفقات</h2></div><div class="attachment-list">@foreach($installation->attachments as $a)<a class="attachment-link" href="{{ route('attachments.download',$a) }}"><span>📎</span><span>{{ $a->label }}<small>{{ $a->original_name }}</small></span></a>@endforeach</div></div>@endif
<div class="card" style="margin-top:18px"><div class="card-header"><h2>المحطات</h2></div><div class="table-wrap"><table><thead><tr><th>المحطة</th><th>PTS</th><th>الحساسات</th><th>التاريخ</th><th>الحالة</th><th>ملاحظات</th></tr></thead><tbody>@foreach($installation->stations as $row)<tr><td>{{ $row->station->name }}</td><td>{{ $row->pts_installed?'تم':'لا' }}</td><td>{{ $row->sensor_count }}</td><td>{{ optional($row->installed_at)->format('Y-m-d')?:'—' }}</td><td>{{ $row->status }}</td><td>{{ $row->notes?:'—' }}</td></tr>@endforeach</tbody></table></div></div>
@endsection
